# Generated by Django 6.0.2 on 2026-02-21 21:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('py', 'python'), ('js', 'JavaScript'), ('c', 'C++'), ('an', 'Android')], verbose_name='Курс')),
                ('course_num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Номер курса')),
                ('start_date', models.DateField(null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(null=True, verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['name', 'course_num'],
                'unique_together': {('name', 'course_num')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)], verbose_name='Возраст')),
                ('gender', models.BooleanField(blank=True, choices=[('m', 'Мужчина'), ('f', 'Женщина')], null=True, verbose_name='Пол')),
                ('active', models.BooleanField(blank=True, null=True, verbose_name='Активный')),
                ('course', models.ManyToManyField(blank=True, related_name='Students', to='main.course', verbose_name='Посещаемые курсы')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('date', models.DateField(null=True, verbose_name='Дата оценки')),
                ('date_add', models.DateField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('date_update', models.DateField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='main.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grades', to='main.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['surname'], name='main_studen_surname_307540_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'surname')},
        ),
    ]
