# Generated by Django 6.0.2 on 2026-02-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Мужской'), ('f', 'Женский')], null=True, verbose_name='Пол'),
        ),
    ]
