# Generated by Django 6.0.2 on 2026-02-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='courses',
        ),
    ]
